import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { build as esbuild } from 'esbuild';
import { generateManifest } from '../compiler/manifest.js';

export interface BuildOptions {
  routes: string;
  /** Directory for generated sources. Default: '.gen'. */
  genDir: string;
  /** Output bundle path. Default: 'dist/server.mjs'. */
  out: string;
  /** Skip bundling; only emit the manifest. */
  manifestOnly?: boolean;
}

export async function buildCommand(options: BuildOptions): Promise<void> {
  const genDir = path.resolve(options.genDir);
  const manifestFile = path.join(genDir, 'routes.ts');

  const { routeCount } = await generateManifest({
    routesDir: path.resolve(options.routes),
    outFile: manifestFile,
  });
  console.log(`[anvil] manifest: ${routeCount} route(s) → ${path.relative(process.cwd(), manifestFile)}`);

  if (options.manifestOnly) return;

  const entryFile = path.join(genDir, 'server.ts');
  await mkdir(genDir, { recursive: true });
  await writeFile(
    entryFile,
    `// Generated by \`anvil build\`. Do not edit.\n` +
      `import { createApp, serve } from 'anvil-sdk';\n` +
      `import { manifest } from './routes.ts';\n\n` +
      `process.env.NODE_ENV ??= 'production';\n` +
      `const app = createApp(manifest);\n` +
      `const server = await serve(app, { port: Number(process.env.PORT) || 3000 });\n` +
      `console.log(\`[anvil] listening on http://localhost:\${server.port}\`);\n`,
    'utf8',
  );

  const outfile = path.resolve(options.out);
  await esbuild({
    entryPoints: [entryFile],
    outfile,
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    packages: 'external',
    sourcemap: true,
    logLevel: 'warning',
  });
  console.log(`[anvil] bundle → ${path.relative(process.cwd(), outfile)}`);
}
