import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { scanRoutes } from './scanner.js';

export interface GenerateOptions {
  routesDir: string;
  /** Output file, e.g. `.gen/routes.ts`. */
  outFile: string;
  /** Import specifier for the framework. Default: 'anvil'. */
  frameworkSpecifier?: string;
}

/**
 * Generate the static route manifest (`.gen/routes.ts`) — statically imports
 * every handler so production builds bundle without filesystem scanning.
 */
export async function generateManifest(options: GenerateOptions): Promise<{ routeCount: number }> {
  const { routes, rootMiddlewareFile } = await scanRoutes(options.routesDir);
  const outFile = path.resolve(options.outFile);
  const outDir = path.dirname(outFile);
  const framework = options.frameworkSpecifier ?? 'anvil';

  const imports: string[] = [];
  const middlewareIds = new Map<string, string>();
  const entries: string[] = [];

  for (const [i, route] of routes.entries()) {
    const routeId = `r${i}`;
    imports.push(`import * as ${routeId} from '${importSpecifier(outDir, route.file)}';`);

    const mwIds: string[] = [];
    for (const file of route.middlewareFiles) {
      let id = middlewareIds.get(file);
      if (!id) {
        id = `m${middlewareIds.size}`;
        middlewareIds.set(file, id);
        imports.push(`import ${id} from '${importSpecifier(outDir, file)}';`);
      }
      mwIds.push(id);
    }

    const segments = JSON.stringify(route.segments);
    const middleware = mwIds.length > 0 ? `[${mwIds.map((id) => `...flat(${id})`).join(', ')}]` : '[]';
    entries.push(
      `    {\n` +
        `      method: '${route.method}',\n` +
        `      pattern: ${JSON.stringify(route.pattern)},\n` +
        `      segments: ${segments},\n` +
        `      handler: ${routeId}.default,\n` +
        `      middleware: ${middleware},\n` +
        `      meta: metaOf(${routeId}),\n` +
        `      file: ${JSON.stringify(path.relative(outDir, route.file).split(path.sep).join('/'))},\n` +
        `    },`,
    );
  }

  let fallback = 'undefined';
  if (rootMiddlewareFile) {
    let id = middlewareIds.get(rootMiddlewareFile);
    if (!id) {
      id = `m${middlewareIds.size}`;
      middlewareIds.set(rootMiddlewareFile, id);
      imports.push(`import ${id} from '${importSpecifier(outDir, rootMiddlewareFile)}';`);
    }
    fallback = `flat(${id})`;
  }

  const code =
    `// Generated by \`anvil build\`. Do not edit.\n` +
    `import type { Manifest, Middleware, RouteMeta } from '${framework}';\n` +
    imports.join('\n') +
    `\n\n` +
    `const flat = (mw: Middleware | Middleware[]): Middleware[] => (Array.isArray(mw) ? mw : [mw]);\n` +
    // Indirect access — a direct `ns.meta` makes esbuild warn when a route file has no meta export.
    `const metaOf = (mod: object): RouteMeta | undefined => (mod as { meta?: RouteMeta }).meta;\n\n` +
    `export const manifest: Manifest = {\n` +
    `  routes: [\n` +
    entries.join('\n') +
    `\n  ],\n` +
    `  fallbackMiddleware: ${fallback},\n` +
    `};\n`;

  await mkdir(outDir, { recursive: true });
  await writeFile(outFile, code, 'utf8');
  return { routeCount: routes.length };
}

/** Relative POSIX import specifier from the manifest to a source file. */
function importSpecifier(fromDir: string, file: string): string {
  let rel = path.relative(fromDir, file).split(path.sep).join('/');
  if (!rel.startsWith('.')) rel = './' + rel;
  return rel;
}
